name: BetaCore
version: 0.3
main: de.wk.betacore.BetaCore
author: linksKeineMitte, YoyoNow, Chaoscaot
api-version: 1.13
description: Ein CoreSystem für Minecraft Server, speziell für WarShip und WarGear Server
loadbefore: [WorldEdit, Brew]
softdepend: [WorldEdit, Brew]
website: https://github.com/EsGibtKeineMitte

commands:
  bau:
    description: Command, um sich zum Bau zu teleportieren
  arena:
    description: Command, um sich zu den Arenen zu teleportien
  core:
    description: Commands für den Core
  l:
    description: Command, um sich zum Bau zu teleportieren
    aliases: hub
  money:
    description: Command für das MoneySystem.
  pc:
    description: Command, um Kanonen automatisch zu beladen.
  gm:
    description: Command, um seinen GameMode zu wechseln
  pi:
    description: Command, um sich Informationen über einen Spieler anzeigen zu lassen.
  cc:
    description: Command, um Custom Commands zu erstellen
  addperm:
    description: Command, um Spielern zusätzlich spezielle Permissions hinzuzufügen.
  pl:
    description: Command, um sich die installierten Plugins anzeigen zu lassen, verbessert.
  si:
    description: Command. um den Spawn zu setzen.
    aliases: serverinfo
  setspawn:
    description: Command, um den Spawn zu setzen
  hub:
  rl:
    description: Ein Core-internen reload Command.
  lag:
    description: Ein Command, um durch Entitys reduzierte Laggs zu reduzieren.
  dev:
    description: Command, um auf den/einen Dev-Server gesenden zu werden.
  schem:
    aliases:
      - /schem
      - /schematic
      - schematic

