name: BetaCore
version: ${project.version}
main: de.wk.betacore.BetaCore
api-version: 1.13
description: Ein CoreSystem für Minecraft Server, speziell für WarShip und WarGear Server

commands:
  bau:
    description: Command, um sich zum Bau zu teleportieren
  arena:
    description: Command, um sich zu den Arenen zu teleportien
  core:
    description: Commands für den Core
