name: BetaCore
version: ${project.version}
main: de.wk.betacore.BetaCore
author: linkskeinemitte
api-version: 1.13
description: Ein CoreSystem für Minecraft Server, speziell für WarShip und WarGear Server

commands:
  bau:
    description: Command, um sich zum Bau zu teleportieren
  arena:
    description: Command, um sich zu den Arenen zu teleportien
  core:
    description: Commands für den Core
  l:
    description: Command, um sich zum Bau zu teleportieren
    aliases: hub
  money:
  pc:
  gm:
    description: Command, um seinen GameMode zu wechseln
  team:
  pi:
    description: Command, um sich Informationen über einen Spieler anzeigen zu lassen.
  cc:
    description: Command, um Custom Commands zu erstellen
  addperm:
    description: Command, um Spielern zusätzlich spezielle Permissions hinzuzufügen.
  pl:
    description: Command, um sich die installierten Plugins anzeigen zu lassen, verbessert.
  si:
  setspawn:
  hub:

