name: BetaCore
version: ${project.version}
main: de.wk.betacore.BetaCore
api-version: 1.13
description: Ein CoreSystem für Minecraft Server, speziell für WarShip und WarGear Server

commands:
  core:
    description: Commands für den Core
